import { useEffect, useRef, useState } from "react";
import { ChevronDown, ChevronRight, Copy, FilePlus2, FileText, Folder, FolderInput, FolderOpen, FolderPlus, FolderTree, Pencil, Trash2 } from "lucide-react";
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuTrigger } from "@/components/ui/context-menu";
import type { Note } from "@/lib/notes";
import { javaBaseTree, notesForFolder, type KnowledgeFolder } from "@/lib/knowledge-tree";

type Props = { notes: Note[]; activeSlug: string; completed: string[]; onOpenNote: (note: Note) => void; createNoteRequest?: number };
type TreeActions = { open: (note: Note) => void; move: (note: Note, folder: KnowledgeFolder) => void; create: (kind: "folder" | "note", folder?: KnowledgeFolder) => void; rename: (note: Note) => void; remove: (note: Note) => void; copyPath: (note: Note) => void; importInto: (folder: KnowledgeFolder) => void };
const initialExpanded = () => new Set(["javabase", "java", "minecraft"]);
const allFolderNotes = (folder: KnowledgeFolder, notes: Note[]): Note[] => folder.children?.length ? folder.children.flatMap((child) => allFolderNotes(child, notes)) : notesForFolder(folder, notes);
async function localRequest(route: string, payload: unknown) { const response = await fetch(`/api/local/${route}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!result.ok) throw new Error(result.error || "本機操作失敗"); }

function TreeNode({ folder, notes, activeSlug, completed, modified, expanded, toggle, actions, depth }: { folder: KnowledgeFolder; notes: Note[]; activeSlug: string; completed: string[]; modified: Record<string, string>; expanded: Set<string>; toggle: (id: string) => void; actions: TreeActions; depth: number }) {
  const isOpen = expanded.has(folder.id); const children = Boolean(folder.children?.length); const directNotes = notesForFolder(folder, notes); const descendants = allFolderNotes(folder, notes); const progress = descendants.length ? Math.round(descendants.filter((note) => completed.includes(note.slug)).length / descendants.length * 100) : 0; const latest = descendants.map((note) => modified[note.path.replace(/^content\//, "")]).filter(Boolean).sort().at(-1);
  return <li>
    <ContextMenu>
      <ContextMenuTrigger asChild>
        <button type="button" onDragOver={(event) => { if (folder.directory) event.preventDefault(); }} onDrop={(event) => { const note = notes.find((item) => item.slug === event.dataTransfer.getData("text/plain")); if (note) actions.move(note, folder); }} onClick={() => toggle(folder.id)} className="flex w-full items-center gap-1.5 rounded-sm px-1.5 py-1.5 text-left text-sm hover:bg-teal-700/[.07] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600" style={{ paddingLeft: `${0.2 + depth * 0.78}rem` }}>{isOpen ? <ChevronDown className="h-3.5 w-3.5 text-teal-800" /> : <ChevronRight className="h-3.5 w-3.5 text-slate-500" />}{isOpen ? <FolderOpen className="h-4 w-4 text-teal-800" /> : <Folder className="h-4 w-4 text-slate-600" />}<span className="min-w-0 flex-1 truncate font-medium">{folder.label}</span><span className="font-mono text-[10px] text-slate-500">{progress}% · {descendants.length}{latest ? ` · ${new Date(latest).toLocaleDateString("zh-TW", { month: "numeric", day: "numeric" })}` : ""}</span></button>
      </ContextMenuTrigger>
      <ContextMenuContent className="min-w-52"><ContextMenuLabel>{folder.label} 資料夾</ContextMenuLabel><ContextMenuSeparator /><ContextMenuItem className="group" title="建立一個新的 Markdown 筆記檔案" onSelect={() => actions.create("note", folder)}><FilePlus2 /><span className="flex flex-col"><span>建立筆記</span><span className="text-[10px] font-normal text-slate-500 group-data-[highlighted]:text-white/75">新增 .md 檔案</span></span></ContextMenuItem><ContextMenuItem className="group" title="在這個資料夾建立子資料夾" onSelect={() => actions.create("folder", folder)}><FolderPlus /><span className="flex flex-col"><span>建立子資料夾</span><span className="text-[10px] font-normal text-slate-500 group-data-[highlighted]:text-white/75">整理學習內容</span></span></ContextMenuItem><ContextMenuItem className="group" title={folder.directory ? "從電腦選擇 Markdown 檔案匯入" : "此資料夾尚未映射實體路徑"} disabled={!folder.directory} onSelect={() => actions.importInto(folder)}><FolderInput /><span className="flex flex-col"><span>從桌面匯入 Markdown</span><span className="text-[10px] font-normal text-slate-500 group-data-[highlighted]:text-white/75">加入既有 .md 檔案</span></span></ContextMenuItem></ContextMenuContent>
    </ContextMenu>
    {isOpen && <ul>{children ? folder.children?.map((child) => <TreeNode key={child.id} folder={child} notes={notes} activeSlug={activeSlug} completed={completed} modified={modified} expanded={expanded} toggle={toggle} actions={actions} depth={depth + 1} />) : directNotes.map((note) => <ContextMenu key={note.slug}><ContextMenuTrigger asChild><li draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", note.slug)}><button type="button" onClick={() => actions.open(note)} className={`flex w-full items-center gap-1.5 rounded-sm py-1.5 text-left text-xs hover:bg-teal-700/[.07] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600 ${note.slug === activeSlug ? "bg-teal-700/[.12] text-teal-950" : "text-slate-700"}`} style={{ paddingLeft: `${1.65 + depth * 0.78}rem` }}><FileText className="h-3.5 w-3.5 text-teal-800" /><span className="truncate">{note.title}</span></button></li></ContextMenuTrigger><ContextMenuContent className="min-w-52"><ContextMenuLabel>{note.title}</ContextMenuLabel><ContextMenuSeparator /><ContextMenuItem title="開啟這篇 Markdown 筆記" onSelect={() => actions.open(note)}><FileText />開啟筆記</ContextMenuItem><ContextMenuItem title="修改這篇筆記的檔名" onSelect={() => actions.rename(note)}><Pencil />重新命名</ContextMenuItem><ContextMenuItem title="複製這篇筆記的相對路徑" onSelect={() => actions.copyPath(note)}><Copy />複製相對路徑</ContextMenuItem><ContextMenuSeparator /><ContextMenuItem title="刪除前會先保存到 local-backups" variant="destructive" onSelect={() => actions.remove(note)}><Trash2 />刪除筆記（保留備份）</ContextMenuItem></ContextMenuContent></ContextMenu>)}</ul>}
  </li>;
}

export function KnowledgeTree({ notes, activeSlug, completed, onOpenNote, createNoteRequest = 0 }: Props) {
  const [expanded, setExpanded] = useState(initialExpanded); const [message, setMessage] = useState(""); const [modified, setModified] = useState<Record<string, string>>({}); const [importFolder, setImportFolder] = useState<KnowledgeFolder | null>(null); const importInputRef = useRef<HTMLInputElement>(null); const lastCreateRequest = useRef(0);
  useEffect(() => { fetch("/api/local/meta").then((response) => response.ok ? response.json() : null).then((result) => setModified(Object.fromEntries((result?.files ?? []).map((file: { path: string; modifiedAt: string }) => [file.path, file.modifiedAt])))).catch(() => undefined); }, []);
  const reload = (text: string) => { setMessage(text); setTimeout(() => location.reload(), 650); };
  const create = async (kind: "folder" | "note", folder?: KnowledgeFolder) => { const name = prompt(kind === "folder" ? "資料夾名稱" : "筆記檔名（可省略 .md）"); if (!name) return; const prefix = folder?.directory ? `${folder.directory}/` : ""; const path = kind === "note" && !name.endsWith(".md") ? `${prefix}${name}.md` : `${prefix}${name}`; try { await localRequest("create", { kind, path, title: name.replace(/\.md$/, "") }); reload("已建立，重新載入中…"); } catch (error) { setMessage(error instanceof Error ? error.message : "建立失敗"); } };
  useEffect(() => { if (createNoteRequest <= lastCreateRequest.current) return; lastCreateRequest.current = createNoteRequest; void create("note"); }, [createNoteRequest]);
  const move = async (note: Note, folder: KnowledgeFolder) => { if (!folder.directory) return setMessage("這個資料夾尚未映射實體路徑。"); const from = note.path.replace(/^content\//, ""); const to = `${folder.directory}/${from.split("/").pop()}`; if (from === to) return; try { await localRequest("move", { from, to }); reload("已移動並備份，重新載入中…"); } catch (error) { setMessage(error instanceof Error ? error.message : "移動失敗"); } };
  const rename = async (note: Note) => { const from = note.path.replace(/^content\//, ""); const name = prompt("新的檔名（.md）", from.split("/").pop()); if (!name) return; try { await localRequest("rename", { from, to: `${from.split("/").slice(0, -1).join("/")}/${name.endsWith(".md") ? name : `${name}.md`}` }); reload("已重新命名並備份，重新載入中…"); } catch (error) { setMessage(error instanceof Error ? error.message : "重新命名失敗"); } };
  const remove = async (note: Note) => { if (!confirm(`刪除「${note.title}」？原始檔案會先保存到 local-backups。`)) return; try { await localRequest("delete", { path: note.path.replace(/^content\//, "") }); reload("已刪除並備份，重新載入中…"); } catch (error) { setMessage(error instanceof Error ? error.message : "刪除失敗"); } };
  const copyPath = async (note: Note) => { try { await navigator.clipboard.writeText(note.path); setMessage("已複製相對路徑。"); } catch { setMessage(`相對路徑：${note.path}`); } };
  const importInto = (folder: KnowledgeFolder) => { if (!folder.directory) return setMessage("這個資料夾尚未映射實體路徑。"); setImportFolder(folder); importInputRef.current?.click(); };
  const importFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file || !importFolder) return; if (!file.name.toLowerCase().endsWith(".md")) return setMessage("只允許匯入 .md 檔案。"); try { await localRequest("import", { directory: importFolder.directory, filename: file.name, content: await file.text() }); reload(`已匯入 ${file.name}，重新載入中…`); } catch (error) { setMessage(error instanceof Error ? error.message : "匯入失敗"); } };
  const actions: TreeActions = { open: onOpenNote, move, create, rename, remove, copyPath, importInto };
  return <nav aria-label="JavaBase 知識庫資料夾" className="border-t border-slate-950/10 pt-3"><input ref={importInputRef} type="file" accept=".md,text/markdown,text/plain" className="sr-only" onChange={importFile} /><div className="mb-2 flex items-center gap-2 px-1"><FolderTree className="h-4 w-4 text-teal-800" /><p className="section-label text-teal-800">KNOWLEDGE FILE TREE</p><button type="button" onClick={() => create("folder")} className="ml-auto rounded p-1 hover:bg-teal-700/10" title="建立資料夾"><FolderPlus className="h-4 w-4" /></button><button type="button" onClick={() => create("note")} className="rounded p-1 hover:bg-teal-700/10" title="建立筆記"><FilePlus2 className="h-4 w-4" /></button></div>{message && <p role="status" className="mb-2 px-1 text-xs text-teal-800">{message}</p>}<ul><TreeNode folder={javaBaseTree} notes={notes} activeSlug={activeSlug} completed={completed} modified={modified} expanded={expanded} toggle={(id) => setExpanded((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; })} actions={actions} depth={0} /></ul></nav>;
}
