/** Design reminder — 藍圖工作桌：編輯區必須清楚區分實體來源、寫入保護與可追溯的變更。 */
import { useEffect, useMemo, useRef, useState, type DragEvent, type KeyboardEvent } from "react";
import { Bold, Code2, ImagePlus, Italic, Link, Save, Table2 } from "lucide-react";
import type { Note } from "@/lib/notes";
import { WikiMarkdown } from "./WikiMarkdown";

type DiskNote = { content: string; hash: string; modifiedAt: string };

export function MarkdownEditor({ note, onOpenNote }: { note: Note; onOpenNote: (note: Note) => void }) {
  const [draft, setDraft] = useState(""); const [hash, setHash] = useState(""); const [status, setStatus] = useState("正在讀取實體 Markdown…"); const [saving, setSaving] = useState(false); const textarea = useRef<HTMLTextAreaElement>(null);
  const relativePath = note.path.replace(/^content\//, "");
  useEffect(() => { let cancelled = false; setStatus("正在讀取實體 Markdown…"); fetch("/api/local/read", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ path: relativePath }) }).then(async (response) => { const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || "無法讀取實體檔案"); return result as DiskNote; }).then((result) => { if (!cancelled) { setDraft(result.content); setHash(result.hash); setStatus(`實體檔案 · 上次修改 ${new Date(result.modifiedAt).toLocaleString("zh-TW")}`); } }).catch(() => { if (!cancelled) { setDraft(note.body); setHash(""); setStatus("本機管理服務未啟動；目前只能預覽，無法安全寫入檔案。"); } }); return () => { cancelled = true; }; }, [note.slug, relativePath, note.body]);
  const previewMarkdown = useMemo(() => draft.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, ""), [draft]);
  const headings = useMemo(() => Array.from(previewMarkdown.matchAll(/^#{2,3}\s+(.+)$/gm), (match) => match[1]), [previewMarkdown]);
  function insert(before: string, after = "") { const target = textarea.current; const start = target?.selectionStart ?? draft.length; const end = target?.selectionEnd ?? start; setDraft(`${draft.slice(0, start)}${before}${draft.slice(start, end)}${after}${draft.slice(end)}`); requestAnimationFrame(() => textarea.current?.focus()); }
  async function save() { if (!hash) { setStatus("找不到實體檔案版本；請以 pnpm dev 開啟本機工作台後再保存。"); return; } setSaving(true); try { const response = await fetch("/api/local/write", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ path: relativePath, content: draft, expectedHash: hash }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || "保存失敗"); setStatus("已寫入實體 Markdown 並建立備份；正在重新載入知識索引…"); setTimeout(() => location.reload(), 650); } catch (error) { setStatus(error instanceof Error ? error.message : "保存失敗"); } finally { setSaving(false); } }
  function onKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void save(); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "b") { event.preventDefault(); insert("**", "**"); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "i") { event.preventDefault(); insert("*", "*"); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); insert("[", "](https://)"); } }
  function onDrop(event: DragEvent<HTMLTextAreaElement>) { event.preventDefault(); const file = event.dataTransfer.files[0]; if (file?.type.startsWith("image/")) insert(`![${file.name}](./images/${file.name})`); }
  return <div className="grid min-h-[64vh] gap-0 overflow-hidden rounded-md border border-slate-950/15 md:grid-cols-2"><section className="border-b border-slate-950/15 bg-slate-950 p-3 md:border-b-0 md:border-r"><div className="mb-2 flex flex-wrap gap-1"><button type="button" onClick={() => insert("**", "**")} aria-label="粗體"><Bold /></button><button type="button" onClick={() => insert("*", "*")} aria-label="斜體"><Italic /></button><button type="button" onClick={() => insert("[", "](https://)")} aria-label="連結"><Link /></button><button type="button" onClick={() => insert("\n| 欄位 | 內容 |\n|---|---|\n| | |\n")} aria-label="表格"><Table2 /></button><button type="button" onClick={() => insert("\n```java\n\n```\n")} aria-label="程式碼區塊"><Code2 /></button><button type="button" onClick={() => insert("\n```mermaid\ngraph TD\n  A[Start] --> B[Note]\n```\n")} aria-label="Mermaid 圖"><ImagePlus /></button><button type="button" onClick={() => void save()} disabled={saving || !hash} className="ml-auto inline-flex items-center gap-1"><Save />{saving ? "寫入中…" : "Ctrl+S 寫入檔案"}</button></div><textarea ref={textarea} value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={onKeyDown} onDrop={onDrop} onDragOver={(event) => event.preventDefault()} className="h-[56vh] w-full resize-none bg-transparent font-mono text-sm leading-6 text-slate-100 outline-none" aria-label="實體 Markdown 編輯器" /></section><section className="overflow-auto bg-[#fffdf7] p-5"><p className="section-label text-teal-800">PREVIEW · PHYSICAL MARKDOWN</p><p role="status" className="mt-2 text-xs leading-5 text-slate-600">{status}</p><div className="mt-3 flex gap-3"><aside className="w-36 shrink-0 text-xs text-slate-500">{headings.map((heading) => <p key={heading} className="mb-2">{heading}</p>)}</aside><article className="min-w-0 flex-1 prose prose-slate max-w-none"><WikiMarkdown markdown={previewMarkdown} onOpenNote={onOpenNote} /></article></div><p className="mt-6 rounded border border-amber-700/20 bg-amber-50 p-3 text-xs text-amber-950">拖放圖片只插入 `./images/檔名` 語法；請將實體圖片放入筆記相對應的 images 資料夾。Ctrl+S 會先比對磁碟版本、建立備份，然後寫回目前的 `.md` 檔案。</p></section></div>;
}
